spring:
  application:
    name: config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/yuyong0214/config-repo
          username: yuyong0214@163.com
          password: 13933177836yu
          basedir: D:\IdeaWorkSpace\sell\config\basedir
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
